### ISSUE TITLE
Could not run mudblood.

### ISSUE THREAD

**Issue by drobati** [talanis85/mudblood-py#1]
```
Traceback (most recent call last):
File "/home/drobati/.virtualenvs/mud/bin/mudblood", line 9, in <module>
    load_entry_point('mudblood==0.1', 'console_scripts', 'mudblood')()
File "/home/drobati/.virtualenvs/mud/local/lib/python2.7/site-packages/mudblood-0.1-py2.7.egg/mudblood/main.py", line 24, in main
    Mudblood(options.i).run(config)
File "/home/drobati/.virtualenvs/mud/local/lib/python2.7/site-packages/mudblood-0.1-py2.7.egg/mudblood/main.py", line 66, in run
    raise Exception("Could not create configuration directory.")
```

 Exception: Could not create configuration directory.

**Comment by drobati** [comment]
Did not read docs/ I'll give that a shot.
